### ISSUE TITLE
mapply

### ISSUE THREAD

**Issue by snoweye** [wrathematics/pbdDMAT#18]
1. I have two distributed matrices, for instance,

if (comm.rank() == 0) {
  X <- matrix(rnorm(n*p,0,1),n,p)
  } else {
  X <- NULL }
if (comm.rank() == 0) {
 Y <- matrix(rnorm(n*p,0,1),p,n)
 } else {
 Y <- NULL }
dX <- as.ddmatrix(X)
dY <- as.ddmatrix(Y)

2. I have a function
f <- function(x,y) x%*%y

3. and this is the result
result <- mapply(f,dX,dY)

**Comment by wrathematics** [comment]
I'm not sure how much sense this makes for a `ddmatrix` (or even a `matrix`).
